import request from './request'
export const apiRegister = data => request.post('/auth/register', data)
export const apiLogin = data => request.post('/auth/login', data)
export const apiMe = () => request.get('/auth/me')
export const apiUpdateProfile = data => request.put('/auth/profile', data)
export const apiSendCode = data => request.post('/auth/send-code', data)
export const apiResetPassword = data => request.post('/auth/reset-password', data)
export const apiDeleteAccount = password => request.delete('/auth/account', { data: { password } })
export const apiUpload = (file, onProgress) => {
  const fd = new FormData()
  fd.append('file', file)
  return request.post('/generate/upload', fd, {
    headers: { 'Content-Type': 'multipart/form-data' },
    onUploadProgress: onProgress
  })
}
export const apiStyles = () => request.get('/generate/styles')
export const apiGenerate = data => request.post('/generate', data)
export const apiGenerateStatus = id => request.get(`/generate/${id}`)
export const apiGenerateBatch = data => request.post('/generate/batch', data)
export const apiBatchStatus = batchId => request.get(`/generate/batch/${batchId}`)
export const apiHistory = params => request.get('/generate', { params })
export const apiDeleteGeneration = id => request.delete(`/generate/${id}`)
export const apiBalance = () => request.get('/credits/balance')
export const apiCreditLogs = params => request.get('/credits/logs', { params })
export const apiPackages = () => request.get('/pay/packages')
export const apiCreateOrder = packageId => request.post('/pay/order', { packageId })
export const apiOrderStatus = id => request.get(`/pay/order/${id}`)
export const apiOrders = params => request.get('/pay/orders', { params })
export const apiMockPay = id => request.post(`/pay/mock/${id}`)
export const apiShare = id => request.post(`/generate/${id}/share`)
export const apiShareInfo = shareId => request.get(`/generate/share/${shareId}`)
export const apiAdvise = fileId => request.post('/generate/advise', { fileId })
export const apiBulk = data => request.post('/generate/bulk', data)
export const apiWorkflowList = () => request.get('/workflow')
export const apiWorkflowGet = id => request.get(`/workflow/${id}`)
export const apiWorkflowCreate = data => request.post('/workflow', data)
export const apiWorkflowUpdate = (id, data) => request.put(`/workflow/${id}`, data)
export const apiWorkflowDelete = id => request.delete(`/workflow/${id}`)
export const apiWorkflowEstimate = (id, graph) => request.post(`/workflow/${id}/estimate`, { graph })
export const apiWorkflowRun = id => request.post(`/workflow/${id}/run`)
export const apiWorkflowRunStatus = runId => request.get(`/workflow/run/${runId}`)
export const apiWorkflowRunCancel = runId => request.post(`/workflow/run/${runId}/cancel`)
export const apiWorkflowRunEventsUrl = runId =>
  `/api/workflow/run/${runId}/events?token=${encodeURIComponent(localStorage.getItem('token') || '')}`
export const apiKeys = () => request.get('/keys')
export const apiCreateKey = name => request.post('/keys', { name })
export const apiRevokeKey = id => request.delete(`/keys/${id}`)
export const apiStatsOverview = () => request.get('/stats/overview')
export const apiAdminUsers = params => request.get('/stats/users', { params })
export const apiAdminAdjustCredits = (id, data) => request.post(`/stats/users/${id}/credits`, data)
export const apiAdminBan = (id, banned) => request.post(`/stats/users/${id}/ban`, { banned })
export const apiAdminGenerations = () => request.get('/stats/generations')
export const apiAdminErrors = () => request.get('/stats/errors')
export const apiAdminRefund = (orderId, reason) => request.post(`/pay/refund/${orderId}`, { reason })
export const apiAdminOrders = params => request.get('/stats/orders', { params })
export const apiAdminDeleteGeneration = id => request.delete(`/stats/generations/${id}`)
export const apiAiMode = () => request.get('/stats/ai-mode')
export const apiSetAiMode = provider => request.post('/stats/ai-mode', { provider })
export const apiAdminSetRole = (id, role) => request.post(`/stats/users/${id}/role`, { role })
export const apiAdminDeleteUser = id => request.delete(`/stats/users/${id}`)
export const apiAdminPackages = () => request.get('/stats/packages')
export const apiAdminCreatePackage = data => request.post('/stats/packages', data)
export const apiAdminUpdatePackage = (id, data) => request.put(`/stats/packages/${id}`, data)
export const apiAdminTogglePackage = id => request.post(`/stats/packages/${id}/toggle`)
